### ISSUE TITLE
lambda_test_bell.cpp generates illegal hardware instruction error when it's called multiple times 

### ISSUE THREAD

**Issue by ahayashi** [ORNL-QCI/qcor#151]
Hi, 

The following is a variant of [lambda_test_bell.cpp](https://github.com/ORNL-QCI/qcor/blob/master/examples/qpu_lambda/lambda_test_bell.cpp), the QJIT compilation, and the kernel execution happen two times consecutively.

```cpp
//  lambda_test_bell_seq.cpp
#include "qcor.hpp"

int bar() {
  set_shots(1024);

  auto x_lambda = qpu_lambda([](qubit q) {
    X(q); });

  auto bell = qpu_lambda([](qreg q) {
    H(q[0]);
    // Call the captured lambda
    x_lambda.ctrl(q[0], q[1]);
    Measure(q);
  }, x_lambda);

  auto q = qalloc(2);
  bell(q);
  q.print();
  qcor_expect(q.counts().size() == 2);
  qcor_expect(q.counts()["00"] > 400);
  qcor_expect(q.counts()["11"] > 400);
  // Entangled...
  qcor_expect(q.counts()["00"] + q.counts()["11"] == 1024);
}

int main(int argc, char **argv) {
    bar();
    bar();
}
```

Here is how I compile and run the original version:
```bash
// original lambda_test_bell.cpp
qcor -qpu qpp lambda_test_bell.cpp
rm -rf ~/.qjit
./a.out
{
    "AcceleratorBuffer": {
        "name": "qrg_nWlrB",
        "size": 2,
        "Information": {},
        "Measurements": {
            "00": 505,
            "11": 519
        }
    }
}
```

Also, here is how I compile and run the variant (lambda_test_bell_seq.cpp):
```bash
// lambda_test_bell_seq.cpp
qcor -qpu qpp lambda_test_bell_seq.cpp
rm -rf ~/.qjit
./a.out
{
    "AcceleratorBuffer": {
        "name": "qrg_nWlrB",
        "size": 2,
        "Information": {},
        "Measurements": {
            "00": 486,
            "11": 538
        }
    }
}
zsh: illegal hardware instruction  ./a.out
```

Looks like the illegal hardware instruction error is generated during the second invocation of `bar()`.
Here are what I observed so far:

- I get the same error even when the lambda is not nested:
```cpp
  auto bell = qpu_lambda([](qreg q) {
    H(q[0]);
    CX(q[0], q[1]);
    Measure(q);
  });
```
- I still have the same error when the lambdas are global.

**Comment by tnguyen-ornl** [comment]
Hi @ahayashi 

Could you please check if the issue still occurs if you return an integer, e.g. `return 0;`, at the end of `bar`? 
Otherwise, changing the signature of `bar` to `void bar()`.

It fixed the problem on my machine. I'll look into why this "warning"-level mistake resulted in this `Illegal instruction` corruption.

**Comment by ahayashi** [comment]
Hi, @tnguyen-ornl,

Thank you for your suggestion. I tried both, but I get another error:

```
rm -rf ~/.qjit
./a.out
{
    "AcceleratorBuffer": {
        "name": "qrg_nWlrB",
        "size": 2,
        "Information": {},
        "Measurements": {
            "00": 511,
            "11": 513
        }
    }
}
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
zsh: abort      ./a.out
```

I have a feeling that this is more related to qjit cache. Did I miss anything?

**Comment by tnguyen-ornl** [comment]
Indeed, so we know that the illegal instruction is due to the `bar` function signature.
Re: this bad_alloc issue, which OS are you using? Is it a MacOS?

**Comment by ahayashi** [comment]
I'm running qcor on a docker container w/ Ubuntu 18.04 image on my mac book pro. I'm not very sure if this docker+mac combination is problematic, but I'd be happy to use an Ubuntu 18.04 machine and see if this happens when I get a chance. FYI, this issue(#138) describes how I build QCOR/XACC from scratch.

**Comment by tnguyen-ornl** [comment]
Hi @ahayashi 

Would you mind trying this DockerFile and let me know if it fixes the problem?
```
FROM ubuntu:18.04
ENV DEBIAN_FRONTEND=noninteractive 
RUN apt-get update && apt-get install -y software-properties-common && apt-add-repository "deb http://archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse"
RUN apt-get update && apt-get install -y wget git gcc-9 g++-9 gfortran-9 python3.8 libpython3.8-dev cmake python3-pip libcurl4-openssl-dev libssl-dev liblapack-dev libblas-dev ninja-build lsb-release 

RUN wget -qO- https://aide-qc.github.io/deploy/aide_qc/debian/PUBLIC-KEY.gpg | apt-key add - \
    && wget -qO- "https://aide-qc.github.io/deploy/aide_qc/debian/$(lsb_release -cs)/aide-qc.list" | tee -a /etc/apt/sources.list.d/aide-qc.list \
    && apt-get update \
    && apt-get install -y aideqc-llvm \
    && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 50 \
    && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 50 \
    && update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-9 50 \
    && git clone --recursive https://github.com/eclipse/xacc && cd xacc && mkdir build && cd build \
    && cmake .. \
    && make -j8 install 

RUN cd ../../ && git clone https://github.com/ORNL-QCI/qcor.git && cd qcor && mkdir build && cd build \
    && cmake .. -DXACC_DIR=~/.xacc -DLLVM_ROOT=/usr/local/aideqc/llvm -DMLIR_DIR=/usr/local/aideqc/llvm/lib/cmake/mlir -DQCOR_BUILD_TESTS=TRUE \
    && make -j8 install && ctest --output-on-failure
```

I tested it with this file: https://github.com/tnguyen-ornl/qcor/blob/tnguyen/check-qpu-lambdas/examples/qpu_lambda/lambda_multiple_bell.cpp and it seems to be okay.

**Comment by ahayashi** [comment]
Thanks @tnguyen-ornl! I'm now building the Dockerfile and will let you know how it goes.

**Comment by ahayashi** [comment]
@tnguyen-ornl it works! For future reference, could you tell what was the cause?

**Comment by tnguyen-ornl** [comment]
I suspect this is due to some low-level incompatibility b/w compiler versions. The only thing that I changed in the above Dockerfile is the `apt-add-repository`, whereby I used the ubuntu 20.04 repo to get the gcc-9, g++-9 packages.

**Comment by ahayashi** [comment]
I see, thanks!
