### ISSUE TITLE
Support C++ syntactic sugar in quantum kernels 

### ISSUE THREAD

**Issue by tnguyen-ornl** [ORNL-QCI/qcor#23]
- Ability to pass literals to kernels:
e.g. `__qpu__ void myKernel(qreg q, int varName)`, we should be able to call `myKernel(q, 0)` (passes `0` to `varName`).
Currently, we need to assign literal to a local variable before passing it to the function argument.

- Ability to assign classical function return values to local classical variables.
e.g. 
```__qpu__ void myKernel(qreg q, int varName) {
std::vector<double> myLocalArray = someFunc(...); // someFunc is strictly classical
```
Currently, this is not available/not reliable. 
We can work around this by modifying the function signature to take the local variable by reference and update it rather than returning a value.

- Ability to do fully-classical conditional.
e.g. 
```
__qpu__ void myKernel(qreg q, int switchVar) {
	if (switchVar != 0) {
		// Do something, e.g. add gates
	}
}
```

Maybe related to the above, early return should also be nice.

e.g.
```
__qpu__ void myKernel(qreg q, int switchVar) {
    if (swicthVar == 0) {
       return;
    }
   // Gates when switchVar != 0
}
```

**Comment by amccaskey** [comment]
why do we need bullet 2? Shouldn't the token_collector_util function see this line, fail to parse with xasm, and then just add it as is to the qrt_code stream?

**Comment by tnguyen-ornl** [comment]
This is a minimal repro:
```
std::vector<double> genArray(int varName) {
  return {};
}

// Entry point kernel
__qpu__ void f(qreg q) {
  const auto nQubits = q.size();
  std::vector<double> angles = genArray(nQubits);
  X(q[0]);
}

// Compile:
// qcor -o test -qpu qpp -qrt test.cpp
int main(int argc, char **argv) {
  // Allocate 10 qubits
  auto q = qalloc(10);
  f(q);
  q.print();
}
```
For some reason, the presence of `std::vector<double> angles = genArray(nQubits);` causes the compilation to fail.

**Comment by amccaskey** [comment]
Ok cool, I can take a look at this.

**Comment by amccaskey** [comment]
This one is caused by bug  in line 108-120 of token_collector_util.cpp 
```cpp
 if (ss.str().find("=") != std::string::npos) {
      // we have a classical var_type var_name = ...;
      int tmp_i = i;
      for (int j = tmp_i;; j--) {
        auto tok = Toks[j];
        if (tok.is(clang::tok::equal)) {
          auto var_name = PP.getSpelling(Toks[j - 1]);
          auto var_type = PP.getSpelling(Toks[j - 2]);
          classical_variables.push_back({var_type, var_name});
          break;
        }
      }
    }
```

see I just assumed a classical variable declaration would be like TYPE NAME = INSTANCE, and thats all the tokens there are. But for std::vector<double> angles, we have tokens std, ::, vector, <, double, >, ...

I can clean this up...

**Comment by tnguyen-ornl** [comment]
This has been implemented. Closing!
