### ISSUE TITLE
installation error on Mac

### ISSUE THREAD

**Issue by ManqobaH** [ORNL-QCI/qcor#91]
I followed the instructions for installation and got the error below:

ld: library not found for -lqir-qrt
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
None
1

**Comment by amccaskey** [comment]
Quick catch - this broke our overnight CI too. I just pushed a fix, pull and try it out.

**Comment by ManqobaH** [comment]
Thank you for your reply. I think it was installed but now have error with importing it. 

For installation, I followed the suggestions from first installation try:
1) Error: 
  homebrew-core is a shallow clone.
  homebrew-cask is a shallow clone.
To `brew update`, first run:
  git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core fetch --unshallow
  git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask fetch --unshallow

2) aide-qc/deploy/qcor 1.0.0 is already installed and up-to-date.
To reinstall 1.0.0, run:
  brew reinstall qcor

3) Then running the printf test, the output was:

./test
{
    "AcceleratorBuffer": {
        "name": "qrg_LRFKq",
        "size": 1,
        "Information": {},
        "Measurements": {
            "0": 493,
            "1": 531
        }
    }
}

However, when I now try to import qcor in Jupyter Notebook, I get the error:

ImportError: dlopen(/usr/local/opt/xacc/_pyxacc.so, 2): Symbol not found: _PyCMethod_New
  Referenced from: /usr/local/opt/xacc/_pyxacc.so
  Expected in: flat namespace
 in /usr/local/opt/xacc/_pyxacc.so

**Comment by amccaskey** [comment]
Can you please document here what OS you are on and the steps you took to install? It may be that on your OS we have built for one standard c++ library while another is present on your system. 

To fully uninstall and then reinstall, you should `brew uninstall xacc llvm-csp qcor`, `brew untap aide-qc/deploy`, and then run the install script again.

**Comment by ManqobaH** [comment]
Thanks for your reply. I am using macOS Catalina version 10.15.7 and the steps I used before are the three steps out-lined in my previous comment. I have now followed the steps you said:

1) `brew uninstall xacc llvm-csp qcor` 
2) `brew untap aide-qc/deploy`
3) `/bin/bash -c "$(curl -fsSL https://aide-qc.github.io/deploy/install.sh)"`
4) `export PYTHONPATH=:/usr/local/opt/xacc:/usr/local/opt/qcor`
5) run printf and test script

The test script is successful unlike the first time, but when importing it in Jupyter Notebook it gives same error. I think the problem is with linking it with the Python API (step 4). The output comment from step 3 said "To use the Python API, please run the following (and add to your .bashrc or .bash_profile)
export PYTHONPATH=:/usr/local/opt/xacc:/usr/local/opt/qcor"

what does it mean to add my own .bashrc. or .bash_profile? I suspect that's the problem.

**Comment by amccaskey** [comment]
In your jupyter notebook, what does 
```python
import sys
print(sys.path)
```
print? Next, from the command line what does this print?
```bash
jupyter kernelspec list
```

My hunch is that your jupyter notebook is using a python version different than the one that qcor/xacc was built against. The first answer [here](https://stackoverflow.com/questions/39007571/running-jupyter-with-multiple-python-and-ipython-paths) talks about potential path issues and how to fix them.

**Comment by ManqobaH** [comment]
Thank you for your patience and support. The outputs of running those codes are below:

`import sys`
`print(sys.path)`

['/Users/manqobahlatshwayo/Desktop/Quantum Computation/Code', '/opt/anaconda3/lib/python37.zip', '/opt/anaconda3/lib/python3.7', '/opt/anaconda3/lib/python3.7/lib-dynload', '', '/Users/manqobahlatshwayo/.local/lib/python3.7/site-packages', '/opt/anaconda3/lib/python3.7/site-packages', '/opt/anaconda3/lib/python3.7/site-packages/aeosa', '/opt/anaconda3/lib/python3.7/site-packages/IPython/extensions', '/Users/manqobahlatshwayo/.ipython']


`jupyter kernelspec list`
Available kernels:
  python3    /opt/anaconda3/share/jupyter/kernels/python3


I do not understand the stack-exchange suggested solution. There seems to be a lot in there, may you please kindly copy and paste here the relevant parts to fix my issue. I don't know what kernel qcor/xacc was built against.

**Comment by amccaskey** [comment]
xacc and qcor are built against the python install from homebrew. the executable is located at /usr/local/bin/python3. Just make sure your Jupyter kernel is running off of that python install.

**Comment by amccaskey** [comment]
I don't use Jupyter often, but I'd think you could achieve this with (from that link)

```bash
/usr/local/bin/python3 -m ipykernel install
```
then select that python kernel in Jupyter.

**Comment by ManqobaH** [comment]
Thank you for your time and help. It didn't work. I also tried it using colab by google and it still didn't work. I'll let it go. Thank you.
