### ISSUE TITLE
Optimize qrt exp() instruction

### ISSUE THREAD

**Issue by tnguyen-ornl** [ORNL-QCI/qcor#92]
The current impl requires a source string construction then XASM compilation.

Looks like the `xasm->compile()` call accounts for ~50-60% of the total `exp()` time. We need to look into optimizing this qrt runtime function.

**Comment by amccaskey** [comment]
Could we replace the xasm string build-up loop with direct calls to quantum::INST() functions?

**Comment by tnguyen-ornl** [comment]
I'm trying something that resembles the existing implementation:
https://github.com/tnguyen-ornl/qcor/commit/9374de14ae9dbd2c336aab0bad69967c6e314f46

The current circuit construction flow is non-linear, which makes it a bit tricky to use qrt calls.
I applied the performance fixes that we learned from optimizing the OpenQASM compilation in XACC for large circuits. 
I'll time the execution to see how much improvement we could get.

**Comment by tnguyen-ornl** [comment]
We're getting ~10x speed-up in this synthetic test https://github.com/tnguyen-ornl/qcor/blob/tnguyen/vqe-benchmark/benchmarks/vqe/qcor/qcor_trotter.py (100 Trotter steps of Heisenberg model of 10, 20, 50, 100 qubits.)

- Before:
```
n instructions = 5700 ; Kernel eval time: 5.635334730148315  [secs]
n instructions = 11700 ; Kernel eval time: 41.47250056266785  [secs] 
```
it was too slow that I needed to stop after two test cases.

- After:
```
n instructions = 5700 ; Kernel eval time: 0.22898435592651367  [secs]
n instructions = 11700 ; Kernel eval time: 0.4970686435699463  [secs]
n instructions = 29700 ; Kernel eval time: 1.3839256763458252  [secs]
n instructions = 59700 ; Kernel eval time: 4.992558240890503  [secs]
```
