### ISSUE TITLE
mlir+qir qubit alias concatenation, and slicing support

### ISSUE THREAD

**Issue by amccaskey** [ORNL-QCI/qcor#98]
We need to support the following alias functionality
```cpp
qubit q[4];
let aliased = q[0, 2, 3];
```
For this we may require an update to the QIR spec to support some kind of `__quantum__rt__array_insert(Array*, i8*, i64)` function. So for this case, you would have MLIR code that allocated a new array of the right size, extracted the Qubit* in the list, and inserted them into the new array.

```cpp
qubit q[2], r[2];
let concatenated = q || r;
```
For this we can leverage `__quantum__rt__array_concatenate(Array*, Array*): Array*`. 

```cpp
qubit q[10];
let subset = q[0:5];
let subset2 = q[5:2:10];
```
Here we will need to define the type `Range == memref<3xi64>`, and then use `__quantum__rt__array_slice(Array*, i32, Range*):Array*`.

Note for ranges: A range is written as a:b or a:c:b where a, b, and c are integers (signed or unsigned). The range corresponds to the set {𝑎,𝑎+𝑐,𝑎+2𝑐,…,𝑎+𝑚𝑐} where 𝑚 is the largest integer such that 𝑎+𝑚𝑐≤𝑏 if 𝑐>0 and 𝑎+𝑚𝑐≥𝑏 if 𝑐<0. If 𝑎=𝑏 then the range corresponds to {𝑎}. Otherwise, the range is the empty set. If 𝑐 is not given, it is assumed to be one, and 𝑐 cannot be zero.

**Comment by amccaskey** [comment]
I don't think we can do the above strictly at the MLIR level - no concept of pointers or bit casting. We'll probably have to make a new Quantum Dialect Op specifically for these extraction operations, and then at the lowering step build up the code snippet you have above.

**Comment by tnguyen-ornl** [comment]
Implementation note: when the aliasing refers to only one qubit, e.g.,
```
let last_qubit = q[3];
```
it needs to return a `Value` of type `Qubit`, not an `Array`.
